substitutions:
  rel1_gpio: GPIO1
  rel2_gpio: GPIO2
  rel3_gpio: GPIO41
  rel4_gpio: GPIO42
  rel5_gpio: GPIO45
  rel6_gpio: GPIO46
  bootkey_gpio: GPIO0
  buzzer_gpio: GPIO21
  led_gpio: GPIO38
  rx_gpio: GPIO17
  tx_gpio: GPIO18

esphome:
  name: espray-6ch
  friendly_name: eSpray-6ch
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    advanced:
      ignore_efuse_mac_crc: false
  flash_size: 8MB

uart:
  rx_pin: $rx_gpio
  tx_pin: $tx_gpio
  baud_rate: 9600

api:
  password: !apisecret

wifi:
  ssid: myssid
  password: !wifisecret

ota:
  safe_mode: true
  port: 3232
  password: !otasecret

logger:
  level: VERBOSE
  # Disable UART logging (used for communication with the display)
  baud_rate: 0

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Budapest
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org

display:
  - platform: nextion
    id: nextion_display
    update_interval: 2s
    lambda: |-
      // Relay states
      char buffer[4];
      for (int i = 0; i < 6; i++) {
        sprintf(buffer, "bt%d", i);
        bool state;
        if (i == 0) state = id(relay1).state;
        else if (i == 1) state = id(relay2).state;
        else if (i == 2) state = id(relay3).state;
        else if (i == 3) state = id(relay4).state;
        else if (i == 4) state = id(relay5).state;
        else if (i == 5) state = id(relay6).state;
        if (state) {
          it.set_component_value(buffer, 1);
        } else {
          it.set_component_value(buffer, 0);
        }
      }
      // Set date&time
      if (id(sntp_time).now().is_valid()) {
        it.set_component_text("time0", id(sntp_time).now().strftime("%H:%M").c_str());
      } else {
        it.set_component_text("time0","NO NTP");
      }
      if (id(sntp_time).now().is_valid()) {
        it.set_component_text("date0", id(sntp_time).now().strftime("%Y-%m-%d").c_str());
      } else {
        it.set_component_text("date0","NO NETWORK");
      }

      // Progress bar&status
      static uint32_t initial_value = 0;
      static bool progress_bar_visible = true;
      if (id(controller).time_remaining_active_valve().has_value()) {
        uint32_t current_zone = id(controller).active_valve().value() + 1;
        uint32_t current_value = id(controller).time_remaining_active_valve().value();
        if (initial_value == 0 || !progress_bar_visible) {
          initial_value = current_value;
          it.show_component("j0");
          it.show_component("state0");
          progress_bar_visible = true;
        }
        int percent_value = static_cast<int>((static_cast<float>(current_value) / initial_value) * 100);
        uint32_t minutes = current_value / 60;
        uint32_t seconds = current_value % 60;
        std::string state_str = "Active: Zone" + std::to_string(current_zone) + "  Duration: " + std::to_string(minutes) + ":" + (seconds < 10 ? "0" : "") + std::to_string(seconds);
        it.set_component_value("j0", percent_value);
        it.set_component_text("state0", state_str.c_str());
      } else {
        if (progress_bar_visible) {
          it.hide_component("j0");
          it.set_component_text("state0", "IDLE");
          progress_bar_visible = false;
          initial_value = 0;
        }
      }

light:
  - platform: esp32_rmt_led_strip
    id: esp32_rgb_led
    name: "Status LED"
    rgb_order: GRB
    pin: GPIO38
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    restore_mode: ALWAYS_OFF
    internal: true

switch:
# Relays
  - platform: gpio
    id: relay1
    pin: $rel1_gpio
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: relay2
    pin: $rel2_gpio
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: relay3
    pin: $rel3_gpio
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: relay4
    pin: $rel4_gpio
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: relay5
    pin: $rel5_gpio
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: relay6
    pin: $rel6_gpio
    restore_mode: RESTORE_DEFAULT_OFF
#Nextion local touch control
  - platform: nextion
    id: bt0_button
    component_name: bt0
    on_turn_on:
        - sprinkler.start_single_valve:
            id: controller
            valve_number: 0
    on_turn_off:
        - sprinkler.shutdown:
            id: controller
        - sprinkler.clear_queued_valves:
            id: controller
  - platform: nextion
    id: bt1_button
    component_name: bt1
    on_turn_on:
        - sprinkler.start_single_valve:
            id: controller
            valve_number: 1
    on_turn_off:
        - sprinkler.shutdown:
            id: controller
        - sprinkler.clear_queued_valves:
            id: controller
  - platform: nextion
    id: bt2_button
    component_name: bt2
    on_turn_on:
        - sprinkler.start_single_valve:
            id: controller
            valve_number: 2
    on_turn_off:
        - sprinkler.shutdown:
            id: controller
        - sprinkler.clear_queued_valves:
            id: controller
  - platform: nextion
    id: bt3_button
    component_name: bt3
    on_turn_on:
        - sprinkler.start_single_valve:
            id: controller
            valve_number: 3
    on_turn_off:
        - sprinkler.shutdown:
            id: controller
        - sprinkler.clear_queued_valves:
            id: controller
  - platform: nextion
    id: bt4_button
    component_name: bt4
    on_turn_on:
        - sprinkler.start_single_valve:
            id: controller
            valve_number: 4
    on_turn_off:
        - sprinkler.shutdown:
            id: controller
        - sprinkler.clear_queued_valves:
            id: controller
  - platform: nextion
    id: bt5_button
    component_name: bt5
    on_turn_on:
        - sprinkler.start_single_valve:
            id: controller
            valve_number: 5
    on_turn_off:
        - sprinkler.shutdown:
            id: controller
        - sprinkler.clear_queued_valves:
            id: controller

interval:
  - interval: 10s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - light.turn_on:
              id: esp32_rgb_led
              brightness: 50%
              red: 0%
              green: 0%
              blue: 100%
        else:
          - light.turn_off:
              id: esp32_rgb_led

sprinkler:
  - id: controller
    main_switch: "Irrigation"
    auto_advance_switch: "Auto Advance"
#   valve_open_delay: 10s
    valves:
      - valve_switch: "Zone 1"
        enable_switch: "Enable Zone 1"
        valve_switch_id: relay1
        run_duration_number:
          id: valve_1_duration
          name: "Zone 1 duration"
          min_value: 1
          max_value: 900
          step: 1
          initial_value: 15
          mode: slider
          icon: mdi:timer-outline
          entity_category: config
          disabled_by_default: false
      - valve_switch: "Zone 2"
        enable_switch: "Enable Zone 2"
        valve_switch_id: relay2
        run_duration_number:
          id: valve_2_duration
          name: "Zone 2 duration"
          min_value: 1
          max_value: 900
          step: 1
          initial_value: 15
          mode: slider
          icon: mdi:timer-outline
          entity_category: config
          disabled_by_default: false
      - valve_switch: "Zone 3"
        enable_switch: "Enable Zone 3"
        valve_switch_id: relay3
        run_duration_number:
          id: valve_3_duration
          name: "Zone 3 duration"
          min_value: 1
          max_value: 900
          step: 1
          initial_value: 15
          mode: slider
          icon: mdi:timer-outline
          entity_category: config
          disabled_by_default: false
      - valve_switch: "Zone 4"
        enable_switch: "Enable Zone 4"
        valve_switch_id: relay4
        run_duration_number:
          id: valve_4_duration
          name: "Zone 4 duration"
          min_value: 1
          max_value: 900
          step: 1
          initial_value: 15
          mode: slider
          icon: mdi:timer-outline
          entity_category: config
          disabled_by_default: false
      - valve_switch: "Zone 5"
        enable_switch: "Enable Zone 5"
        valve_switch_id: relay5
        run_duration_number:
          id: valve_5_duration
          name: "Zone 5 duration"
          min_value: 1
          max_value: 900
          step: 1
          initial_value: 15
          mode: slider
          icon: mdi:timer-outline
          entity_category: config
          disabled_by_default: false
      - valve_switch: "Zone 6"
        enable_switch: "Enable Zone 6"
        valve_switch_id: relay6
        run_duration_number:
          id: valve_6_duration
          name: "Zone 6 duration"
          min_value: 1
          max_value: 900
          step: 1
          initial_value: 15
          mode: slider
          icon: mdi:timer-outline
          entity_category: config
          disabled_by_default: false
